extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_sm64_material_001_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_lights;
extern u8 castle_grounds_dl_texture_09_ci4[];
extern u8 castle_grounds_dl_texture_09_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_texture_02_ci4[];
extern u8 castle_grounds_dl_texture_02_ci4_pal_rgba16[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[28];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_1[470];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_castle_grounds_dl_sm64_material_001[];
extern Gfx mat_revert_castle_grounds_dl_sm64_material_001[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
